project:
  type: website
  output-dir: docs

website:
  title: "Simplify diagnosis"
  navbar:
    left:
      - about.qmd
      - how.qmd
      - faq.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    search: false



